version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  flower:
    image: mher/flower
    container_name: flower
    environment:
      CELERY_BROKER_URL: "pyamqp://guest:guest@rabbitmq:5672//"
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

  celery_worker:
    build:
      context: .
    command: celery -A src.controller.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure the correct Dockerfile is used
    ports:
      - "8123:8123"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      PORT: 8123  # Pass the port explicitly if required by the app
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:
